namespace ResData
{
    using System;

    public enum RES_SRV2CLT_GLOBAL_CONF_TYPE
    {
        RES_SRV2CLT_GLOBAL_CONF_TYPE_LOGIN_ACTIVITY_POP_NUM,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_PVPCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_TASKCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_FRIENDCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_SINGLECOIN_NUM,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_MAX
    }
}

