namespace ResData
{
    using System;

    public enum RES_PVP_ACHIEVEMENT_MULTI_KILL_TYPE
    {
        RES_STAR_CONDITION_ACHIEVEMENT_DOUBLE_KILL = 3,
        RES_STAR_CONDITION_ACHIEVEMENT_FIRST_KILL = 1,
        RES_STAR_CONDITION_ACHIEVEMENT_KILL = 2,
        RES_STAR_CONDITION_ACHIEVEMENT_PENTA_KILL = 6,
        RES_STAR_CONDITION_ACHIEVEMENT_QUATARY_KILL = 5,
        RES_STAR_CONDITION_ACHIEVEMENT_TRIPLE_KILL = 4
    }
}

