namespace ResData
{
    using System;

    public enum RES_ROLLINGMSG_TYPE
    {
        RES_ROLLINGMSG_NONE,
        RES_ROLLINGMSG_RAREHERO_LUCKYDRAW,
        RES_ROLLINGMSG_RARESKIN_LUCKYDRAW,
        RES_ROLLINGMSG_SYMBOL,
        RES_ROLLINGMSG_NOBE,
        RES_ROLLINGMSG_RANKGRADE,
        RES_ROLLINGMSG_CONSTANTWIN,
        RES_ROLLINGMSG_GIFT_HERO,
        RES_ROLLINGMSG_GIFT_SKIN,
        RES_ROLLINGMSG_MAX
    }
}

