namespace CSProtocol
{
    using System;

    public enum COM_ACNT_NEWCLIENT_BITS_TYPE
    {
        COM_ACNT_NEWCLIENT_BITS_TYPE_NEWBITGIFT_SHOW,
        COM_ACNT_NEWCLIENT_BITS_TYPE_PROPITEM_ADD,
        COM_ACNT_NEWCLIENT_BITS_TYPE_GIFTITEM_ADD,
        COM_ACNT_NEWCLIENT_BITS_TYPE_MAX
    }
}

