namespace CSProtocol
{
    using System;

    public enum COM_PLATFORM_STATISTIC_TYPE
    {
        COM_PLATFORM_STATISTIC_TYPE_NULL,
        COM_PLATFORM_STATISTIC_TYPE_GODLIKE,
        COM_PLATFORM_STATISTIC_TYPE_DEAD,
        COM_PLATFORM_STATISTIC_TYPE_KILL,
        COM_PLATFORM_STATISTIC_TYPE_MAX
    }
}

