namespace CSProtocol
{
    using System;

    public enum CS_BUYHEROSKIN_ERRCODE
    {
        CS_BUYHEROSKIN_FORBID_COUPONS = 3,
        CS_BUYHEROSKIN_FORBID_DIAMOND = 9,
        CS_BUYHEROSKIN_FORBID_GOLD = 2,
        CS_BUYHEROSKIN_FORBID_LACKCOIN = 11,
        CS_BUYHEROSKIN_FORBID_MIXPAY = 10,
        CS_BUYHEROSKIN_FORBID_SHOW = 13,
        CS_BUYHEROSKIN_FORBID_SKINCOIN = 8,
        CS_BUYHEROSKIN_NO_HERO = 6,
        CS_BUYHEROSKIN_NO_SKIN = 5,
        CS_BUYHEROSKIN_OTHER = 7,
        CS_BUYHEROSKIN_OWNED = 1,
        CS_BUYHEROSKIN_PAY_COUPONS = 4,
        CS_BUYHEROSKIN_TIME_ERROR = 12
    }
}

