//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipTable")]
  public partial class EquipTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public EquipTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Part;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Part", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Part
    {
      get { return _Part; }
      set { _Part = value; }
    }
    private int _BaseAtk;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"BaseAtk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BaseAtk
    {
      get { return _BaseAtk; }
      set { _BaseAtk = value; }
    }
    private int _CappedAtk;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"CappedAtk", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int CappedAtk
    {
      get { return _CappedAtk; }
      set { _CappedAtk = value; }
    }
    private int _DamageRate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"DamageRate", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int DamageRate
    {
      get { return _DamageRate; }
      set { _DamageRate = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Type LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Type = source.ReadInt32();
                    break;
                    
            case 3:   //Part LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Part = source.ReadString();
                    break;
                    
            case 4:   //BaseAtk LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    BaseAtk = source.ReadInt32();
                    break;
                    
            case 5:   //CappedAtk LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    CappedAtk = source.ReadInt32();
                    break;
                    
            case 6:   //DamageRate LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    DamageRate = source.ReadInt32();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}