//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemTable")]
  public partial class ItemTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public ItemTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private ProtoTable.ItemTable.eType _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTable.ItemTable.eType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Detail;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Detail
    {
      get { return _Detail; }
      set { _Detail = value; }
    }
    private string _DrawSource;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DrawSource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DrawSource
    {
      get { return _DrawSource; }
      set { _DrawSource = value; }
    }
    private int _GetExp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"GetExp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int GetExp
    {
      get { return _GetExp; }
      set { _GetExp = value; }
    }
    private int _SaleExp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"SaleExp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SaleExp
    {
      get { return _SaleExp; }
      set { _SaleExp = value; }
    }
    private int _SalePrice;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"SalePrice", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int SalePrice
    {
      get { return _SalePrice; }
      set { _SalePrice = value; }
    }
    private int _Lv;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Material = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"Material", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Material
    {
      get { return _Material; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _ProficiencyId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"ProficiencyId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> ProficiencyId
    {
      get { return _ProficiencyId; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eType")]
    public enum eType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Weapon", Value=1)]
      Weapon = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cloth", Value=2)]
      Cloth = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Jewelry", Value=3)]
      Jewelry = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cuisine", Value=4)]
      Cuisine = 4
    }
  
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Type LABEL_REQUIRED TYPE_ENUM .ProtoTable.ItemTable.eType TwosComplement
                    Type = (ProtoTable.ItemTable.eType)source.ReadInt32();
                    break;
                    
            case 3:   //Name LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Name = source.ReadString();
                    break;
                    
            case 4:   //Detail LABEL_REQUIRED TYPE_STRING  TwosComplement
                    Detail = source.ReadString();
                    break;
                    
            case 5:   //DrawSource LABEL_REQUIRED TYPE_STRING  TwosComplement
                    DrawSource = source.ReadString();
                    break;
                    
            case 6:   //GetExp LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    GetExp = source.ReadInt32();
                    break;
                    
            case 7:   //SaleExp LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    SaleExp = source.ReadInt32();
                    break;
                    
            case 8:   //SalePrice LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    SalePrice = source.ReadInt32();
                    break;
                    
            case 9:   //Lv LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Lv = source.ReadInt32();
                    break;
                    
            case 10:   //Material LABEL_REPEATED TYPE_STRING  TwosComplement
                    int Materialfield = source.FieldNumber;
                    do{
                        Material.Add(source.ReadString());
                    } while(source.TryReadFieldHeader(Materialfield));
                    break;
                    
            case 11:   //ProficiencyId LABEL_REPEATED TYPE_SINT32  ZigZag
                    int ProficiencyIdfield = source.FieldNumber;
                    do{
                        source.Hint(ProtoBuf.WireType.SignedVariant); 
                        ProficiencyId.Add(source.ReadInt32());
                    } while(source.TryReadFieldHeader(ProficiencyIdfield));
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}