//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemAttrTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemAttrTable")]
  public partial class ItemAttrTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public ItemAttrTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _ReduceMaterial = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ReduceMaterial", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> ReduceMaterial
    {
      get { return _ReduceMaterial; }
    }
  
    private int _ReduceTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ReduceTime", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ReduceTime
    {
      get { return _ReduceTime; }
      set { _ReduceTime = value; }
    }
    private int _QualityUp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"QualityUp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int QualityUp
    {
      get { return _QualityUp; }
      set { _QualityUp = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //ReduceMaterial LABEL_REPEATED TYPE_STRING  TwosComplement
                    int ReduceMaterialfield = source.FieldNumber;
                    do{
                        ReduceMaterial.Add(source.ReadString());
                    } while(source.TryReadFieldHeader(ReduceMaterialfield));
                    break;
                    
            case 3:   //ReduceTime LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ReduceTime = source.ReadInt32();
                    break;
                    
            case 4:   //QualityUp LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    QualityUp = source.ReadInt32();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}