//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProficiencyTable.proto
namespace ProtoTable
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProficiencyTable")]
  public partial class ProficiencyTable : global::ProtoBuf.IExtensible,global::ProtoBuf.IParseable
  {
    public ProficiencyTable() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Lv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Lv", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Lv
    {
      get { return _Lv; }
      set { _Lv = value; }
    }
    private int _Count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private int _BuffId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"BuffId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int BuffId
    {
      get { return _BuffId; }
      set { _BuffId = value; }
    }
    public void Parse(ProtoBuf.ProtoReader source){
        int fieldNumber = 0;
        while ((fieldNumber = source.ReadFieldHeader()) > 0)
        {
            switch (fieldNumber)
            {
                default:
                    source.SkipField();
                    break;
            
    
            case 1:   //ID LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    ID = source.ReadInt32();
                    break;
                    
            case 2:   //Lv LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Lv = source.ReadInt32();
                    break;
                    
            case 3:   //Count LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    Count = source.ReadInt32();
                    break;
                    
            case 4:   //BuffId LABEL_REQUIRED TYPE_SINT32  ZigZag
                    source.Hint(ProtoBuf.WireType.SignedVariant); 
                    BuffId = source.ReadInt32();
                    break;
                    
            }
        }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}